// Klook destination map: post `region` -> Klook city id + slug (+country as a
// guard record). Sources & verification, 2026-08-07:
//  - id/slug pairs: Klook's own sitemap-city-plain_en-us.xml (1,462 cities) —
//    never guessed; a name that is not in the sitemap is simply not mapped.
//  - same-name-city risk: every candidate whose name exists in another country
//    (Valencia, Granada, San Sebastian, George Town, Naples, Hyderabad) was
//    opened on klook.com and its country confirmed against the post corpus.
//  - `widget: true` marks the 16 cities confirmed in the Travelpayouts price
//    widget dropdown. The others get the destination LINK only — an unverified
//    city_id fed to the widget renders an empty box, a link cannot.
// Regenerate candidates with: Klook city sitemap x post regions (see the
// 2026-08-07 session notes); keys must match a post's `region` exactly.
export interface KlookCity { id: number; slug: string; country: string; widget?: boolean }

export const KLOOK_CITY: Record<string, KlookCity> = {
  "Seoul": { id: 13, slug: 'seoul', country: 'South Korea', widget: true },
  "Busan": { id: 46, slug: 'busan', country: 'South Korea', widget: true },
  "Incheon": { id: 158, slug: 'incheon', country: 'South Korea', widget: true },
  "Tokyo": { id: 28, slug: 'tokyo', country: 'Japan', widget: true },
  "Osaka": { id: 29, slug: 'osaka', country: 'Japan', widget: true },
  "Kyoto": { id: 30, slug: 'kyoto', country: 'Japan', widget: true },
  "Fukuoka": { id: 5209, slug: 'fukuoka-prefecture', country: 'Japan', widget: true },
  "Sapporo": { id: 133938, slug: 'sapporo', country: 'Japan', widget: true },
  "Okinawa": { id: 6484, slug: 'okinawa-prefecture', country: 'Japan', widget: true },
  "Nagoya": { id: 71, slug: 'nagoya', country: 'Japan', widget: true },
  "Nara": { id: 7062, slug: 'nara-prefecture', country: 'Japan', widget: true },
  "Hiroshima": { id: 5122, slug: 'hiroshima-prefecture', country: 'Japan', widget: true },
  "Bangkok": { id: 4, slug: 'bangkok', country: 'Thailand', widget: true },
  "Phuket": { id: 7, slug: 'phuket', country: 'Thailand', widget: true },
  "Shanghai": { id: 59, slug: 'shanghai', country: 'China', widget: true },
  "Xi'an": { id: 60, slug: 'xi-an', country: 'China', widget: true },
  "Beijing": { id: 57, slug: 'beijing', country: "China" },
  "Chengdu": { id: 61, slug: 'chengdu', country: "China" },
  "Guangzhou": { id: 12146, slug: 'guangzhou', country: "China" },
  "Guilin": { id: 62, slug: 'guilin', country: "China" },
  "Hangzhou": { id: 19190, slug: 'hangzhou', country: "China" },
  "Hong Kong": { id: 2, slug: 'hong-kong', country: "China" },
  "Qingdao": { id: 14950, slug: 'qingdao', country: "China" },
  "Shenzhen": { id: 23301, slug: 'shenzhen', country: "China" },
  "Suzhou": { id: 16549, slug: 'suzhou', country: "China" },
  "Wuhan": { id: 24369, slug: 'wuhan', country: "China" },
  "Lyon": { id: 365009, slug: 'lyon', country: "France" },
  "Marseille": { id: 185152, slug: 'marseille', country: "France" },
  "Nice": { id: 169424, slug: 'nice', country: "France" },
  "Paris": { id: 107, slug: 'paris', country: "France" },
  "Strasbourg": { id: 365224, slug: 'strasbourg', country: "France" },
  "Agra": { id: 214, slug: 'agra', country: "India" },
  "Chandigarh": { id: 12871, slug: 'chandigarh', country: "India" },
  "Delhi": { id: 145, slug: 'delhi', country: "India" },
  "Hyderabad": { id: 252, slug: 'hyderabad', country: "India" },
  "Jaipur": { id: 149, slug: 'jaipur', country: "India" },
  "Mumbai": { id: 132, slug: 'mumbai', country: "India" },
  "Udaipur": { id: 150, slug: 'udaipur', country: "India" },
  "Varanasi": { id: 211, slug: 'varanasi', country: "India" },
  "Bali": { id: 8, slug: 'bali', country: "Indonesia" },
  "Bandung": { id: 209, slug: 'bandung', country: "Indonesia" },
  "Jakarta": { id: 45, slug: 'jakarta', country: "Indonesia" },
  "Labuan Bajo": { id: 522, slug: 'labuan-bajo', country: "Indonesia" },
  "Surabaya": { id: 337, slug: 'surabaya', country: "Indonesia" },
  "Yogyakarta": { id: 163, slug: 'yogyakarta', country: "Indonesia" },
  "Bologna": { id: 340, slug: 'bologna', country: "Italy" },
  "Florence": { id: 115, slug: 'florence', country: "Italy" },
  "Milan": { id: 79468, slug: 'milan', country: "Italy" },
  "Naples": { id: 126, slug: 'naples', country: "Italy" },
  "Rome": { id: 92, slug: 'rome', country: "Italy" },
  "Siena": { id: 317, slug: 'siena', country: "Italy" },
  "Turin": { id: 322, slug: 'turin', country: "Italy" },
  "Venice": { id: 117, slug: 'venice', country: "Italy" },
  "Verona": { id: 339, slug: 'verona', country: "Italy" },
  "Aomori": { id: 14493, slug: 'aomori', country: "Japan" },
  "Chiba": { id: 22069, slug: 'chiba', country: "Japan" },
  "Kanazawa": { id: 445, slug: 'kanazawa', country: "Japan" },
  "Yokohama": { id: 26895, slug: 'yokohama', country: "Japan" },
  "George Town": { id: 365161, slug: 'george-town', country: "Malaysia" },
  "Ipoh": { id: 266, slug: 'ipoh', country: "Malaysia" },
  "Johor Bahru": { id: 191, slug: 'johor-bahru', country: "Malaysia" },
  "Kota Kinabalu": { id: 364959, slug: 'kota-kinabalu', country: "Malaysia" },
  "Kuala Lumpur": { id: 49, slug: 'kuala-lumpur', country: "Malaysia" },
  "Langkawi": { id: 190, slug: 'langkawi', country: "Malaysia" },
  "Penang": { id: 65, slug: 'penang', country: "Malaysia" },
  "Bohol": { id: 144, slug: 'bohol', country: "Philippines" },
  "Cebu": { id: 97, slug: 'cebu', country: "Philippines" },
  "Davao": { id: 331, slug: 'davao', country: "Philippines" },
  "Makati": { id: 10908, slug: 'makati', country: "Philippines" },
  "Manila": { id: 96, slug: 'manila', country: "Philippines" },
  "Palawan": { id: 121, slug: 'palawan', country: "Philippines" },
  "Taguig": { id: 26802, slug: 'taguig', country: "Philippines" },
  "Singapore": { id: 6, slug: 'singapore', country: "Singapore" },
  "Andong": { id: 8898, slug: 'andong', country: "South Korea" },
  "Daegu": { id: 545, slug: 'daegu', country: "South Korea" },
  "Gyeongju": { id: 8928, slug: 'gyeongju', country: "South Korea" },
  "Jeju": { id: 20544, slug: 'jeju', country: "South Korea" },
  "Pohang": { id: 705582, slug: 'pohang', country: "South Korea" },
  "Sokcho": { id: 11054, slug: 'sokcho', country: "South Korea" },
  "Yeosu": { id: 703649, slug: 'yeosu', country: "South Korea" },
  "Barcelona": { id: 108, slug: 'barcelona', country: "Spain" },
  "Bilbao": { id: 494, slug: 'bilbao', country: "Spain" },
  "Granada": { id: 495, slug: 'granada', country: "Spain" },
  "Madrid": { id: 109, slug: 'madrid', country: "Spain" },
  "Malaga": { id: 35920, slug: 'malaga', country: "Spain" },
  "San Sebastian": { id: 493, slug: 'san-sebastian', country: "Spain" },
  "Seville": { id: 122, slug: 'seville', country: "Spain" },
  "Valencia": { id: 381, slug: 'valencia', country: "Spain" },
  "Hualien": { id: 20, slug: 'hualien', country: "Taiwan" },
  "Kaohsiung": { id: 22, slug: 'kaohsiung', country: "Taiwan" },
  "Nantou": { id: 25303, slug: 'nantou', country: "Taiwan" },
  "New Taipei": { id: 6488, slug: 'new-taipei', country: "Taiwan" },
  "Taichung": { id: 25, slug: 'taichung', country: "Taiwan" },
  "Tainan": { id: 164, slug: 'tainan', country: "Taiwan" },
  "Taipei": { id: 19, slug: 'taipei', country: "Taiwan" },
  "Taitung": { id: 47, slug: 'taitung', country: "Taiwan" },
  "Ayutthaya": { id: 701356, slug: 'ayutthaya', country: "Thailand" },
  "Chiang Mai": { id: 5, slug: 'chiang-mai', country: "Thailand" },
  "Chiang Rai": { id: 216, slug: 'chiang-rai', country: "Thailand" },
  "Krabi": { id: 63, slug: 'krabi', country: "Thailand" },
  "Pattaya": { id: 17, slug: 'pattaya', country: "Thailand" },
  "Antalya": { id: 269, slug: 'antalya', country: "Turkey" },
  "Bodrum": { id: 116609, slug: 'bodrum', country: "Turkey" },
  "Cappadocia": { id: 270, slug: 'cappadocia', country: "Turkey" },
  "Istanbul": { id: 186, slug: 'istanbul', country: "Turkey" },
  "Izmir": { id: 701631, slug: 'izmir', country: "Turkey" },
  "Abu Dhabi": { id: 131, slug: 'abu-dhabi', country: "United Arab Emirates" },
  "Ajman": { id: 703511, slug: 'ajman', country: "United Arab Emirates" },
  "Al Ain": { id: 703500, slug: 'al-ain', country: "United Arab Emirates" },
  "Dubai": { id: 78, slug: 'dubai', country: "United Arab Emirates" },
  "Ras Al Khaimah": { id: 442, slug: 'ras-al-khaimah', country: "United Arab Emirates" },
  "Sharjah": { id: 426, slug: 'sharjah', country: "United Arab Emirates" },
  "Arlington": { id: 137040, slug: 'arlington', country: "United States" },
  "Chicago": { id: 701807, slug: 'chicago', country: "United States" },
  "Las Vegas": { id: 136, slug: 'las-vegas', country: "United States" },
  "Los Angeles": { id: 124, slug: 'los-angeles', country: "United States" },
  "New Orleans": { id: 557, slug: 'new-orleans', country: "United States" },
  "New York": { id: 93, slug: 'new-york', country: "United States" },
  "San Francisco": { id: 129, slug: 'san-francisco', country: "United States" },
  "Seattle": { id: 465, slug: 'seattle', country: "United States" },
  "Da Nang": { id: 74, slug: 'da-nang', country: "Vietnam" },
  "Hanoi": { id: 34, slug: 'hanoi', country: "Vietnam" },
  "Ho Chi Minh City": { id: 33, slug: 'ho-chi-minh-city', country: "Vietnam" },
  "Hoi An": { id: 75, slug: 'hoi-an', country: "Vietnam" },
  "Hue": { id: 35, slug: 'hue', country: "Vietnam" },
  "Nha Trang": { id: 208, slug: 'nha-trang', country: "Vietnam" },
  "Phu Quoc": { id: 130, slug: 'phu-quoc', country: "Vietnam" },
};

// City-level Klook landing URL: the curated destination page when the city is
// mapped, the search page only as a last resort (Klook's robots.txt disallows
// /search/, so a mapped city must never fall back to it).
export function klookCityDest(city: string, locale: string): string {
  const m = KLOOK_CITY[city];
  return m
    ? `https://www.klook.com/${locale}/destination/c${m.id}-${m.slug}/`
    : `https://www.klook.com/${locale}/search/?query=${encodeURIComponent(city)}`;
}
