export const LANGS = ['en', 'ko', 'ja', 'es', 'zh'];

const COPY = {
  en: { subjectSingle: 'This week in {region}', preheaderSingle: 'New guides from {region}, just published →', editorNote: "Every week we send you only the new guides from the place you follow. Here's {region}, freshly published.", sectionLabel: "This week's guides", eventsLabel: 'Upcoming events', ctaSingle: 'Explore all {region} guides', alsoNew: 'Also new across {country}', read: 'Read the guide →', unsubscribe: 'Unsubscribe', langLabel: 'Language', regionChange: 'Change your region', weeklyEdit: 'The Weekly Edit', subjectGlobal: 'The best of Wander Atlas this week', preheaderGlobal: "This week's most notable new guides →", editorNoteGlobal: "No single place this week — just the guides our editors couldn't stop talking about.", ctaGlobal: 'See all this week’s guides', sectionMulti: 'Your places this week' },
  ko: { subjectSingle: '이번 주 {region} 소식', preheaderSingle: '{region}에서 새로 발행된 가이드 →', editorNote: '매주 관심 지역의 새 글만 모아 보내드려요. 이번 주 {region} 소식입니다.', sectionLabel: '이번 주의 가이드', eventsLabel: '다가오는 이벤트', ctaSingle: '{region} 가이드 전체 보기', alsoNew: '{country}의 다른 새 글', read: '가이드 읽기 →', unsubscribe: '구독 취소', langLabel: '언어', regionChange: '지역 변경', weeklyEdit: '주간 에디트', subjectGlobal: '이번 주 Wander Atlas 베스트', preheaderGlobal: '이번 주 가장 주목할 새 가이드 →', editorNoteGlobal: '이번 주는 특정 지역 없이, 편집자들이 계속 이야기한 가이드만 모았어요.', ctaGlobal: '이번 주 가이드 전체 보기', sectionMulti: '이번 주 내 관심 지역' },
  ja: { subjectSingle: '今週の{region}', preheaderSingle: '{region}の新着ガイド →', editorNote: '毎週、フォロー中の地域の新着ガイドだけをお届けします。今週の{region}です。', sectionLabel: '今週のガイド', eventsLabel: '近日開催のイベント', ctaSingle: '{region}のガイドをすべて見る', alsoNew: '{country}のその他の新着', read: 'ガイドを読む →', unsubscribe: '配信停止', langLabel: '言語', regionChange: '地域を変更', weeklyEdit: 'ウィークリー・エディット', subjectGlobal: '今週のWander Atlasベスト', preheaderGlobal: '今週の注目の新着ガイド →', editorNoteGlobal: '今週は特定の地域ではなく、編集者が注目したガイドを集めました。', ctaGlobal: '今週のガイドをすべて見る', sectionMulti: '今週のフォロー地域' },
  es: { subjectSingle: 'Esta semana en {region}', preheaderSingle: 'Nuevas guías de {region}, recién publicadas →', editorNote: 'Cada semana te enviamos solo las guías nuevas del lugar que sigues. Aquí tienes {region}.', sectionLabel: 'Las guías de esta semana', eventsLabel: 'Próximos eventos', ctaSingle: 'Ver todas las guías de {region}', alsoNew: 'También nuevo en {country}', read: 'Leer la guía →', unsubscribe: 'Cancelar suscripción', langLabel: 'Idioma', regionChange: 'Cambiar región', weeklyEdit: 'La edición semanal', subjectGlobal: 'Lo mejor de Wander Atlas esta semana', preheaderGlobal: 'Las guías nuevas más destacadas de la semana →', editorNoteGlobal: 'Esta semana no hay un solo lugar: solo las guías de las que no paran de hablar nuestros editores.', ctaGlobal: 'Ver todas las guías de esta semana', sectionMulti: 'Tus lugares esta semana' },
  zh: { subjectSingle: '本周{region}', preheaderSingle: '{region}最新发布的攻略 →', editorNote: '我们每周只为你发送所关注地区的最新攻略。这是本周的{region}。', sectionLabel: '本周攻略', eventsLabel: '即将举行的活动', ctaSingle: '查看{region}的全部攻略', alsoNew: '{country}的其他新内容', read: '阅读攻略 →', unsubscribe: '取消订阅', langLabel: '语言', regionChange: '更换地区', weeklyEdit: '每周精选', subjectGlobal: '本周 Wander Atlas 精选', preheaderGlobal: '本周最值得关注的新攻略 →', editorNoteGlobal: '本周不限单一地区，只精选编辑们最推荐的攻略。', ctaGlobal: '查看本周全部攻略', sectionMulti: '本周你关注的地区' },
};

export function copyFor(lang) {
  return COPY[lang] || COPY.en;
}

export function fill(str, vars = {}) {
  return String(str).replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? vars[k] : `{${k}}`));
}
